Back to TCP (UDP doesn't like being re-used...  Success/failure indication

diff --git a/test_lb b/test_lb
--- a/test_lb
+++ b/test_lb
@@ -5,5 +5,10 @@ vppctl clear trace
 vppctl trace add af-packet-input 20
 # Need this running to listen:
 # nc -uvlk4 127.0.0.4 3000
-nc -uv4 127.0.0.2 3000
+if echo -n "DATA!!!\n" | nc -4v -q0 127.0.0.2 3000
+then
+    echo "SUCCESS!!!"
+else
+    echo "Failed (netcat rc=$?)"
+fi
 vppctl show trace > "$(dirname $0)/latest_output"
